export const ADD_NOMINEE = 'ADD_NOMINEE';
export const ADD_NOMINEES_FROM_LS = 'ADD_NOMINEES_FROM_LS';
export const REMOVE_NOMINEE = 'REMOVE_NOMINEE';
export const GET_RESULTS = 'GET_RESULTS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const FINISHED_NOMINATING = 'FINISHED_NOMINATING';
